# Generated by the protocol buffer compiler.  DO NOT EDIT!

from __google.protobuf import descriptor
from __google.protobuf import message
from __google.protobuf import reflection
#from __google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='signals.proto',
  package='MoNav',
  serialized_pb='\n\rsignals.proto\x12\x05MoNav\"{\n\x0b\x43ommandType\x12&\n\x05value\x18\x01 \x02(\x0e\x32\x17.MoNav.CommandType.Type\"D\n\x04Type\x12\x13\n\x0fVERSION_COMMAND\x10\x01\x12\x13\n\x0fROUTING_COMMAND\x10\x02\x12\x12\n\x0eUNPACK_COMMAND\x10\x03\"\x10\n\x0eVersionCommand\" \n\rVersionResult\x12\x0f\n\x07version\x18\x01 \x02(\t\"[\n\x04Node\x12\x10\n\x08latitude\x18\x01 \x02(\x01\x12\x11\n\tlongitude\x18\x02 \x02(\x01\x12\x1a\n\x0fheading_penalty\x18\x03 \x01(\x01:\x01\x30\x12\x12\n\x07heading\x18\x04 \x01(\x01:\x01\x30\"i\n\x04\x45\x64ge\x12\x12\n\nn_segments\x18\x01 \x02(\r\x12\x0f\n\x07name_id\x18\x02 \x01(\r\x12\x0f\n\x07type_id\x18\x03 \x01(\r\x12\x0f\n\x07seconds\x18\x04 \x01(\r\x12\x1a\n\x12\x62ranching_possible\x18\x05 \x01(\x08\"\x88\x01\n\x0eRoutingCommand\x12\x16\n\x0e\x64\x61ta_directory\x18\x01 \x02(\t\x12\x1c\n\rlookup_radius\x18\x02 \x01(\x01:\x05\x31\x30\x30\x30\x30\x12 \n\x11lookup_edge_names\x18\x03 \x01(\x08:\x05\x66\x61lse\x12\x1e\n\twaypoints\x18\x04 \x03(\x0b\x32\x0b.MoNav.Node\"\xa4\x02\n\rRoutingResult\x12\'\n\x04type\x18\x01 \x02(\x0e\x32\x19.MoNav.RoutingResult.Type\x12\x0f\n\x07seconds\x18\x02 \x01(\x01\x12\x1a\n\x05nodes\x18\x03 \x03(\x0b\x32\x0b.MoNav.Node\x12\x1a\n\x05\x65\x64ges\x18\x04 \x03(\x0b\x32\x0b.MoNav.Edge\x12\x12\n\nedge_names\x18\x05 \x03(\t\x12\x12\n\nedge_types\x18\x06 \x03(\t\"y\n\x04Type\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0f\n\x0bLOAD_FAILED\x10\x02\x12\x11\n\rLOOKUP_FAILED\x10\x03\x12\x10\n\x0cROUTE_FAILED\x10\x04\x12\x16\n\x12NAME_LOOKUP_FAILED\x10\x05\x12\x16\n\x12TYPE_LOOKUP_FAILED\x10\x06\"D\n\rUnpackCommand\x12\x17\n\x0fmap_module_file\x18\x01 \x02(\t\x12\x1a\n\x0b\x64\x65lete_file\x18\x02 \x01(\x08:\x05\x66\x61lse\"_\n\x0cUnpackResult\x12&\n\x04type\x18\x01 \x02(\x0e\x32\x18.MoNav.UnpackResult.Type\"\'\n\x04Type\x12\x0b\n\x07SUCCESS\x10\x01\x12\x12\n\x0e\x46\x41IL_UNPACKING\x10\x02')



_COMMANDTYPE_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='MoNav.CommandType.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='VERSION_COMMAND', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ROUTING_COMMAND', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UNPACK_COMMAND', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=79,
  serialized_end=147,
)

_ROUTINGRESULT_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='MoNav.RoutingResult.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LOAD_FAILED', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LOOKUP_FAILED', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ROUTE_FAILED', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NAME_LOOKUP_FAILED', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_LOOKUP_FAILED', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=712,
  serialized_end=833,
)

_UNPACKRESULT_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='MoNav.UnpackResult.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FAIL_UNPACKING', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=961,
  serialized_end=1000,
)


_COMMANDTYPE = descriptor.Descriptor(
  name='CommandType',
  full_name='MoNav.CommandType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='MoNav.CommandType.value', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMMANDTYPE_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=147,
)


_VERSIONCOMMAND = descriptor.Descriptor(
  name='VersionCommand',
  full_name='MoNav.VersionCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=149,
  serialized_end=165,
)


_VERSIONRESULT = descriptor.Descriptor(
  name='VersionResult',
  full_name='MoNav.VersionResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='MoNav.VersionResult.version', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=167,
  serialized_end=199,
)


_NODE = descriptor.Descriptor(
  name='Node',
  full_name='MoNav.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='latitude', full_name='MoNav.Node.latitude', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='longitude', full_name='MoNav.Node.longitude', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='heading_penalty', full_name='MoNav.Node.heading_penalty', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='heading', full_name='MoNav.Node.heading', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=201,
  serialized_end=292,
)


_EDGE = descriptor.Descriptor(
  name='Edge',
  full_name='MoNav.Edge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='n_segments', full_name='MoNav.Edge.n_segments', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name_id', full_name='MoNav.Edge.name_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type_id', full_name='MoNav.Edge.type_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='seconds', full_name='MoNav.Edge.seconds', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='branching_possible', full_name='MoNav.Edge.branching_possible', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=294,
  serialized_end=399,
)


_ROUTINGCOMMAND = descriptor.Descriptor(
  name='RoutingCommand',
  full_name='MoNav.RoutingCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='data_directory', full_name='MoNav.RoutingCommand.data_directory', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lookup_radius', full_name='MoNav.RoutingCommand.lookup_radius', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=10000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lookup_edge_names', full_name='MoNav.RoutingCommand.lookup_edge_names', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='waypoints', full_name='MoNav.RoutingCommand.waypoints', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=402,
  serialized_end=538,
)


_ROUTINGRESULT = descriptor.Descriptor(
  name='RoutingResult',
  full_name='MoNav.RoutingResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='MoNav.RoutingResult.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='seconds', full_name='MoNav.RoutingResult.seconds', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nodes', full_name='MoNav.RoutingResult.nodes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='edges', full_name='MoNav.RoutingResult.edges', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='edge_names', full_name='MoNav.RoutingResult.edge_names', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='edge_types', full_name='MoNav.RoutingResult.edge_types', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ROUTINGRESULT_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=541,
  serialized_end=833,
)


_UNPACKCOMMAND = descriptor.Descriptor(
  name='UnpackCommand',
  full_name='MoNav.UnpackCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='map_module_file', full_name='MoNav.UnpackCommand.map_module_file', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='delete_file', full_name='MoNav.UnpackCommand.delete_file', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=835,
  serialized_end=903,
)


_UNPACKRESULT = descriptor.Descriptor(
  name='UnpackResult',
  full_name='MoNav.UnpackResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='MoNav.UnpackResult.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _UNPACKRESULT_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=905,
  serialized_end=1000,
)

_COMMANDTYPE.fields_by_name['value'].enum_type = _COMMANDTYPE_TYPE
_COMMANDTYPE_TYPE.containing_type = _COMMANDTYPE;
_ROUTINGCOMMAND.fields_by_name['waypoints'].message_type = _NODE
_ROUTINGRESULT.fields_by_name['type'].enum_type = _ROUTINGRESULT_TYPE
_ROUTINGRESULT.fields_by_name['nodes'].message_type = _NODE
_ROUTINGRESULT.fields_by_name['edges'].message_type = _EDGE
_ROUTINGRESULT_TYPE.containing_type = _ROUTINGRESULT;
_UNPACKRESULT.fields_by_name['type'].enum_type = _UNPACKRESULT_TYPE
_UNPACKRESULT_TYPE.containing_type = _UNPACKRESULT;
DESCRIPTOR.message_types_by_name['CommandType'] = _COMMANDTYPE
DESCRIPTOR.message_types_by_name['VersionCommand'] = _VERSIONCOMMAND
DESCRIPTOR.message_types_by_name['VersionResult'] = _VERSIONRESULT
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Edge'] = _EDGE
DESCRIPTOR.message_types_by_name['RoutingCommand'] = _ROUTINGCOMMAND
DESCRIPTOR.message_types_by_name['RoutingResult'] = _ROUTINGRESULT
DESCRIPTOR.message_types_by_name['UnpackCommand'] = _UNPACKCOMMAND
DESCRIPTOR.message_types_by_name['UnpackResult'] = _UNPACKRESULT

class CommandType(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMANDTYPE
  
  # @@protoc_insertion_point(class_scope:MoNav.CommandType)

class VersionCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VERSIONCOMMAND
  
  # @@protoc_insertion_point(class_scope:MoNav.VersionCommand)

class VersionResult(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VERSIONRESULT
  
  # @@protoc_insertion_point(class_scope:MoNav.VersionResult)

class Node(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NODE
  
  # @@protoc_insertion_point(class_scope:MoNav.Node)

class Edge(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EDGE
  
  # @@protoc_insertion_point(class_scope:MoNav.Edge)

class RoutingCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROUTINGCOMMAND
  
  # @@protoc_insertion_point(class_scope:MoNav.RoutingCommand)

class RoutingResult(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROUTINGRESULT
  
  # @@protoc_insertion_point(class_scope:MoNav.RoutingResult)

class UnpackCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UNPACKCOMMAND
  
  # @@protoc_insertion_point(class_scope:MoNav.UnpackCommand)

class UnpackResult(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UNPACKRESULT
  
  # @@protoc_insertion_point(class_scope:MoNav.UnpackResult)

# @@protoc_insertion_point(module_scope)
